### ISSUE TITLE
error in itemTuples() ? 

### ISSUE THREAD

**Issue by peterhalpin** [beckerbenj/eatATA#1]
Hello, I am working through some examples with your package -- I like the workflow very much and the documentation is very helpful. 

I have run into the following error

R > item_pool <- data.frame(items = paste("item", 1:6), 
...                         stems = paste("stem", rep(1:3, each = 2)))

R > grm_items <- stemInclusionTuples(items = item_pool, 
...                                  idCol = "items", 
...                                  stemCol = "stems")
Error in do.call(rbind, out_list) : second argument must be a list

The error appears to be in line 60 of the itemTuples() function. The object "out_list" is not a list, it is a matrix created by the preceding "apply" call.  

Apologies that I cannot suggest a correction at this point in time as I am still trying to sort out what the returns are supposed to be.

**Comment by peterhalpin** [comment]
More digging...

The example provided with the documentation for stemInclusionTuples does work: 

    # Example data.frame
    inclDF <- data.frame(ID = paste0("item_", 1:6),
              stem = c(rep("stim_1", 3), "stim_3", "stim_4", "stim_3"),
              stringsAsFactors = FALSE)
    
    # Create tuples
    stemInclusionTuples(inclDF, idCol = "ID", stemCol = "stem")

But when you change the example so that there is no stem with only a single item, it breaks (change "stim_4" to "stim_3")

R > inclDF2 <- data.frame(ID = paste0("item_", 1:6),
...           stem = c(rep("stim_1", 3), "stim_3", "stim_3", "stim_3"),
...           stringsAsFactors = FALSE)
R > 
R > stemInclusionTuples(inclDF2, idCol = "ID", stemCol = "stem")
Error in do.call(rbind, out_list) : second argument must be a list

**Comment by peterhalpin** [comment]
This worked for me. Perhaps you will find it helpful too. 

# Wrapper on base::combn
comb2 <- function(items){ 
  if (length(items) > 1) {t(combn(items, 2))} else {NULL}
} 

# To produce same functionality as stemInclusionTuples() 
testlets <- function(items, stems) {
  stem.ids <- unique(stems)
  pairwise_list <- lapply(stem.ids, function(x) comb2(items[stems == x]))
  Reduce(rbind, pairwise_list)  
} 
# Examples and output

R > # Example 1 (from eatATA documentation)
R > inclDF <- data.frame(ID = paste0("item_", 1:6),
...           stem = c(rep("stim_1", 3), "stim_3", "stim_4", "stim_3"))

R > testlets(items = inclDF$ID, stems = inclDF$stem)
     [,1]     [,2]    
[1,] "item_1" "item_2"
[2,] "item_1" "item_3"
[3,] "item_2" "item_3"
[4,] "item_4" "item_6"
R > stemInclusionTuples(inclDF, "ID", stemCol = "stem")
     [,1]     [,2]    
[1,] "item_1" "item_2"
[2,] "item_1" "item_3"
[3,] "item_2" "item_3"
[4,] "item_4" "item_6"

R > # Example 2 (the one that breaks)
R > inclDF2 <- data.frame(ID = paste0("item_", 1:6),
...           stem = c(rep("stim_1", 3), "stim_3", "stim_3", "stim_3"))       

R > testlets(items = inclDF2$ID, stems = inclDF2$stem)
     [,1]     [,2]    
[1,] "item_1" "item_2"
[2,] "item_1" "item_3"
[3,] "item_2" "item_3"
[4,] "item_4" "item_5"
[5,] "item_4" "item_6"
[6,] "item_5" "item_6"

**Comment by beckerbenj** [comment]
Thank you for this bug report!

This was indeed a bug in itemTuples(), only occuring when all items with inclusions or exclusions had the exact same amount of inclusions or exclusions. The bug was due to the inconsistent output structure of the apply()-function, which in such cases was a matrix instead of the internally expected list. This should be fixed now with the latest Github commit.
