### ISSUE TITLE
Test failure with dev version of lpSolve

### ISSUE THREAD

**Issue by gaborcsardi** [beckerbenj/eatATA#4]
I am about to submit a new version of lpSolve (https://github.com/gaborcsardi/lpSolve) to CRAN, and unfortunately it seems to make one of your test cases fail:

```
══ Failed tests ════════════════════════════════════════════════════════════════
── Failure ('test_inspectSolution.R:27:3'): inspect solution ───────────────────
out[[1]]$ID not equal to c(paste0("item_", c(1, 3, 5, 8, 10)), NA).
2/6 mismatches
x[1]: "item_2"
y[1]: "item_1"

x[3]: "item_6"
y[3]: "item_5"
── Failure ('test_inspectSolution.R:37:3'): inspect solution complete items data.frame ──
out[[1]]$ID not equal to paste0("item_", c(1, 3, 5, 8, 10)).
2/5 mismatches
x[1]: "item_2"
y[1]: "item_1"

x[3]: "item_6"
y[3]: "item_5"

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 549 ]
```

It seems that the problem in this file is not deterministic, and the test is testing one possible solution only, and the (completely unrelated) change in lpSolve triggers another solution. This is the solution with the new version of lpSolve:
```
Browse[2]> out[[1]]
         ID itemValues format
2    item_2         -4     mc
3    item_3         -2     mc
6    item_6         -1   open
8    item_8         20   open
10  item_10          0   open
Sum    <NA>         13   <NA>
```

I'll submit lpSolve to CRAN later today, so I am afraid that CRAN will make you update your package as well.

**Comment by gaborcsardi** [comment]
Actually, my submission did not trigger any reverse dependency failures on CRAN, so maybe you don't need to update right away. Other CRAN platforms might fail later, though.

**Comment by beckerbenj** [comment]
Thanks for pointing out the non-deterministic problem! We will fix the test anyway, so it won't lead to any issues in future reverse dependency checks.

**Comment by gaborcsardi** [comment]
🚀
